name: {{ cookiecutter.project_name|lower|replace(' ', '_') }}_platform_interface
description: A common platform interface for the {{ cookiecutter.project_name }} plugin.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0
  json_annotation: ^4.4.0
  framework_contracts_flutter:
    git:
      url: git@github.com:discovery-ltd/v1-framework-contracts-flutter.git
      ref: master
      path: framework_contracts_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.2
  json_serializable: ^6.1.1