name: {{ cookiecutter.project_name|lower|replace(' ', '_') }}
description: The main {{ cookiecutter.project_name }} plugin.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.17.0"

dependencies:
  flutter:
    sdk: flutter
  {{ cookiecutter.project_name|lower|replace(' ', '_') }}_android:
    git:
      url: git@github.com:discovery-ltd/v1-{{ cookiecutter.project_name|lower|replace(' ', '-') }}-plugin.git
      path: {{ cookiecutter.project_name|lower|replace(' ', '_') }}_android
      ref: master #plugin
  {{ cookiecutter.project_name|lower|replace(' ', '_') }}_ios:
    git:
      url: git@github.com:discovery-ltd/v1-{{ cookiecutter.project_name|lower|replace(' ', '-') }}-plugin.git
      path: {{ cookiecutter.project_name|lower|replace(' ', '_') }}_ios
      ref: master #plugin
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  plugin_platform_interface: ^2.1.0

flutter:
  plugin:
    platforms:
      android:
        default_package: {{ cookiecutter.project_name|lower|replace(' ', '_') }}_android
      ios:
        default_package: {{ cookiecutter.project_name|lower|replace(' ', '_') }}_ios