## Symlinked from bundle_utils/Gemfile

source 'https://rubygems.org'

gem 'cocoapods', '~> 1.11.0'
gem 'fastlane', '>= 2.178'
gem 'cmess'
gem 'titleize'
gem 'xcode-install'
gem 'xcov'
gem 'danger-xcov'